### ISSUE TITLE
feat: talk with AIMentor

### ISSUE THREAD

**Issue by javenisme** [SCCA-EDU/AIMentor#7]
1. Give ChatGPT AI a realistic human voice by connecting [ElevenLabs](https://elevenlabs.com) text-to-speech account, or using your browser's built-in text-to-speech.

2. Speech recognition powered by OpenAI Whisper.

reference: https://github.com/cogentapps/chat-with-gpt

EST: 1h

**Comment by SuZhou-Joe** [comment]
So, this issue wants to add a voice icon aside message, once clicked, it will read out by using the ElevenLabs service?

**Comment by SuZhou-Joe** [comment]
Please add ElevenLabs APIKey inside this issue.

**Comment by javenisme** [comment]
added API Key in Doppler
