### ISSUE TITLE
feat: public prompts space

### ISSUE THREAD

**Issue by javenisme** [SCCA-EDU/AIMentor#8]
Import the attached prompts.csv file as a `default` prompts folder
1. everyone can access default(public) prompts folder
2. can not delete/edit this folder content
3. default prompts support Chinese and English 

EST:1H

reference: 

The `Promptbar.tsx` is a React component that provides a user interface where users can create, update, and delete prompts. This component uses multiple custom React hooks and contexts to manage state and perform actions.

Here are the main parts of this component:

1. **Using Contexts and Hooks**: This component uses multiple contexts and hooks to get and manage state. For example, it uses `HomeContext` to get and update the `showPromptbar` state, which determines whether the prompt bar is shown. It also uses the `useFolders` and `usePrompts` hooks to get and update the state of folders and prompts.

4. **Handler Functions**: This component defines several handler functions to perform actions, such as `handleTogglePromptbar` (toggle the display state of the prompt bar), `handleCreatePrompt` (create a new prompt), `handleDeletePrompt` (delete a prompt), `handleUpdatePrompt` (update a prompt), and `handleDrop` (handle drag and drop events).

5. **Searching and Filtering Prompts**: This component uses the `useEffect` hook to listen for changes in `searchTerm` and `prompts`, and filters prompts based on the search term.

6. **Rendering**: In the rendering part, this component uses `PromptbarContext.Provider` to provide context, and then uses the `Sidebar` component to display the prompt bar. It also passes several props and child components to `Sidebar`, such as `isOpen` (whether the prompt bar is open), `addItemButtonTitle` (the title of the add item button), `itemComponent` (the item component), `folderComponent` (the folder component), etc.

Regarding how to save and read the prompts created by users, this component uses the `usePrompts` hook to get and update the state of prompts. This hook may use some form of persistent storage (such as local storage or a database) to save and read data. The specific implementation may be in the definition of the `usePrompts` hook, but this file does not provide the code for this part. You may need to look at the source code of the `usePrompts` hook to get more information.

**Comment by javenisme** [comment]
[prompts.csv](https://github.com/SCCA-EDU/AIMentor/files/11659807/prompts.csv)

**Comment by SuZhou-Joe** [comment]
The prompts are stored in mongodb.

So this issue is about to import those default prompts into the db when first deployed or on-demand?

**Comment by SuZhou-Joe** [comment]
| Task | Additional info | Effort |
|----------|----------|----------|
|   Translate prompts to Chinese   |  -   |   0.5h   |
|   Handle csv files in FE  |   1. add a csv package to parse csv file in FE 2. add language detect  |   0.5h   |
|   Promptsbar.tsx enhancement   |   1. use hooks to update state of promptsList   |   0.5h   |
